### ISSUE TITLE
Staker can get away with increasing stake even though inactive for epochs

### ISSUE THREAD

**Issue by agatsoh** [razor-network/contracts#10]
Consider a hypothetical example
Suppose Staker stakes in 4000 Epoch and for some reason becomes offline for 9 Epochs. Then comes online again in 4010 Epoch and then increases stake and then in the same Epoch commits and reveals. So in this way he can avoid penalty for not participating for the last 9 Epochs. This is a bug.

**Comment by hrishikeshio** [comment]
Seems #115 solved this.
@doctoc @abhishekvispute reopen if not fixed.
