### ISSUE TITLE
To ensure all jobs are being fulfilled at the time of block proposal.

### ISSUE THREAD

**Issue by SamAg19** [razor-network/contracts#105]
**Describe the bug**
A proposed staker can propose a block that does not fulfill all the jobs if confirmed. There needs to be check regarding this before a block is proposed to the network

**To Reproduce**
1. Propose a block that fulfills only 2 jobs, even though there are 4 jobs ongoing in the network.
2. The proposal is successful.

**Expected behavior**
The staker should not be able to propose such a block as all jobs need to be present in each block proposal.

** Solution **
1. Introduce a new state (#190)
2. Keep track of active assets in each epoch.

**Comment by SkandaBhat** [comment]
#190 (Add new state) is part of the solution for this.

**Comment by SkandaBhat** [comment]
This has a dependency on #206 and #135.

We need to keep track of how many assets needs to be fulfilled in the current epoch.
