### ISSUE TITLE
Inherit ACL contract in SchellingCoin Contract not OZ's AccesControl.

### ISSUE THREAD

**Issue by dev1644** [razor-network/contracts#111]
**Describe the bug**

Currently, `SchellingCoin` inherits OZ's AccesControl contract, it should be inheriting `ACL` contract instead because `Admin Role` is being set up in `ACL` contract itself.

**Comment by adi44** [comment]
@dev1644 I have made a pull request #114

**Comment by dev1644** [comment]
This has been taken care of in #117
