### ISSUE TITLE
Create issues from WARNING and TODO in codebase

### ISSUE THREAD

**Issue by dev1644** [razor-network/contracts#112]
**Describe the bug**
There are two bug warnings that are marked in the contract codebase, the objective is to analyze and resolve those warnings

Warning 1 -: https://github.com/razor-network/contracts/blob/73ebea04c978693f16249c556ba622a121817a24/contracts/Core/StakeManager.sol#L93

Warning 2 -: https://github.com/razor-network/contracts/blob/73ebea04c978693f16249c556ba622a121817a24/contracts/Core/StakeManager.sol#L339

**Comment by hrishikeshio** [comment]
There are also multiple "TODO"s. some of them may have created vulnerabilities. These need to be analyzed and resolved also.

**Comment by SkandaBhat** [comment]
We need to create new issues and track them. Closing this.

**Comment by adi44** [comment]
#172 #171
