### ISSUE TITLE
fix bugs as reported by internal audit

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/contracts#133]
**Describe the bug**
fix the bugs as reported by the internal audit. The file is shared internally.

**Comment by ashish10677** [comment]
@hrishikeshio can we run the internal audit once more so that I can start fixing the issues. Since it was run the last time, a lot of code has been changed.
cc @SkandaBhat @abhishekvispute

**Comment by abhishekvispute** [comment]
Hey @ashish10677 
We would be doing it post we merge AssignJobsRandomly and Addition of New State
