### ISSUE TITLE
Assign Collections Randomly

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#135]
**Is your feature request related to a problem? Please describe.**
We have to optimise merkle proof computation.

**Describe the solution you'd like**
- Assign Jobs to stakers randomly solves this problem.
- Number of jobs assigned to each staker needs to be decided by governance parameter

**Comment by SkandaBhat** [comment]
Is related to #46.

**Comment by abhishekvispute** [comment]
And its back 🚀

**Comment by SkandaBhat** [comment]
This has a dependency on #582
