### ISSUE TITLE
Correct Migration for Shelling Coin 

### ISSUE THREAD

**Issue by abhishekvispute** [razor-network/contracts#141]
**Describe the bug**
As per current migration script, StateManager is passed as minter to shelling coin
We don't need that
https://github.com/razor-network/contracts/blob/8f59a1e78f886bedb433c1fcd3592af1296753f6/migrations/src/8_deploy_schelling_coin_and_faucet.js#L12

We can remove this as well
https://github.com/razor-network/contracts/blob/8f59a1e78f886bedb433c1fcd3592af1296753f6/contracts/SchellingCoin.sol#L26

we don't need to pass default minter in constructor only 
if admin wants he can always add him as minter

**Comment by SkandaBhat** [comment]
Closing this as it is included in #108
