### ISSUE TITLE
Have a common contract for Structs, Dissolves Structs library.

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#144]
A library can't have its own state, any call from a contract → library is a delegate call, so the contract keeps those data in storage, not a library, This is confusing enough &, to be honest, I am not sure what is the storage layout for it (~~I need to do some testing).~~ I have done some testing, it looks like in our codebase we are deploying contracts with inheriting `Structs.sol` implementation (through storage contracts). I have done some preliminary gas-usage testing, if we have a common storage contract for these struct definitions & use this contract there is no difference in gas cost.

~~In a recent issue (@Abhishek Vispute) have encountered a problem with size restriction (~23kb) of contract, its highly possible that in future we will be using proxy pattern and will splitting the logic of our contract across multiple contracts to bypass this size limit. There we need to make sure that the Storage layout will persist across all proxies and logic contract~~. Even though this was due to multiple inheriting of the same contract, but it quite possible that in future we might have a similar predicament, Ignoring the size limit I still think have a common storage contract is a better & clean way.

I have not seen code that declares state in the library (if I recall correctly <0.6.0 compilers don't allow that, so I am still sceptical about storing structs in the library),

Update -: The behaviour of the above-discussed approach is similar to the declaration in a contract in our case, Struct library is explicitly called for a particular Struct so it's not being deployed & linked rather than being used as a data definition type, this is still not a known design & my conclusion is based upon my testing only. I would prefer to rather drop Structs Lib in favour of a common Storage contract.

**Comment by hrishikeshio** [comment]
> A library can't have its own state, any call from a contract → library is a delegate call, so the contract keeps those data in storage, not a library, This is confusing enough &, to be honest, I am not sure what is the storage layout for it (~I need to do some testing).~ I have done some testing, it looks like in our codebase we are deploying contracts with inheriting `Structs.sol` implementation (through storage contracts). I have done some preliminary gas-usage testing, if we have a common storage contract for these struct definitions & use this contract there is no difference in gas cost.
> 
> ~~In a recent issue (@abhishek Vispute) have encountered a problem with size restriction (~23kb) of contract, its highly possible that in future we will be using proxy pattern and will splitting the logic of our contract across multiple contracts to bypass this size limit. There we need to make sure that the Storage layout will persist across all proxies and logic contract~~. Even though this was due to multiple inheriting of the same contract, but it quite possible that in future we might have a similar predicament, Ignoring the size limit I still think have a common storage contract is a better & clean way.
> 
> I have not seen code that declares state in the library (if I recall correctly <0.6.0 compilers don't allow that, so I am still sceptical about storing structs in the library),
> 
> Update -: The behaviour of the above-discussed approach is similar to the declaration in a contract in our case, Struct library is explicitly called for a particular Struct so it's not being deployed & linked rather than being used as a data definition type, this is still not a known design & my conclusion is based upon my testing only. I would prefer to rather drop Structs Lib in favour of a common Storage contract.

I don't see any justification to convert it to a library. Adding `wontfix` for now as more analysis is needed.
