### ISSUE TITLE
finalizeDispute edge case

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#151]
**Describe the bug**
If there is only one block and that is an invalid block, then the next epoch will have problems in stakeManager.

Lets not penalise in this case.

**Comment by SkandaBhat** [comment]
Shekhar please pick this up

**Comment by GaurShekhar** [comment]
Sure

**Comment by GaurShekhar** [comment]
I think this thing is taken care in StakeManager _givePenalties() function.

Here we are already checking that the lowerCutoffsLastEpoch length value should be greater than zero.

Check the code here :
https://github.com/razor-network/contracts/blob/e10eda8750deffca33076fca2434a061537126a5/contracts/Core/StakeManager.sol#L396

**Comment by GaurShekhar** [comment]
TEST CASE:

This is being tested in BlcokManger test cases:

 1- all blocks being disputed
 2- no block should be confirmed in the previous epoch

These two test cases cover the edge case we have mentioned in the above issue.  
Check the Test Case here:
https://github.com/razor-network/contracts/blob/351b43a49d4b327253063d635de36fe88d1cdb68/test/BlockManager.js#L303

**Comment by SkandaBhat** [comment]
Write a few assertions to check rewards and penalties (no rewards and penalties should be applied)
