### ISSUE TITLE
Make Slashing penalty as a governance parameter

### ISSUE THREAD

**Issue by abhishekvispute** [razor-network/contracts#152]
**Describe the bug**
As of now slashing penalty is hardcoded, we need to make it a gov parameter and reduce it,
as directly slashing to 0 is too strict.

**Comment by SkandaBhat** [comment]
@GauravJain9 Please pick this up

**Comment by GauravJain9** [comment]
@SkandaBhat  ok

**Comment by GauravJain9** [comment]
Generated a PR for this  @SkandaBhat  
https://github.com/razor-network/contracts/pull/157#issue-667868202
