### ISSUE TITLE
Fail build if linting fails

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#176]
**Is your feature request related to a problem? Please describe.**
We want to fail CI build and not run tests if linting fails. This is to prevent hyegine level issues that are currently being addressed on PR reviews.

**Describe the solution you'd like**
Fail Travis build if hyegine checks fail.

**Comment by hrishikeshio** [comment]
I think this is solved?

**Comment by SkandaBhat** [comment]
Yes. Closing this.
