### ISSUE TITLE
Tx is reverted because rewards > reward pool

### ISSUE THREAD

**Issue by adi44** [razor-network/contracts#178]
We have to analyse why rewards is greater than reward pool. Could be rewards are being calculated wrong or could be a deeper issue.

**Comment by abhishekvispute** [comment]
Hey @adi44 
Can you please elaborate this, like in which case its happening

**Comment by adi44** [comment]
Hi @abhishekvispute 

so after every few epochs it happens that all stakers commit, but one staker fails to reveal.

**Comment by SkandaBhat** [comment]
Please use this for more context - https://dashboard.tenderly.co/tx/mumbai/0xb7deaedff9479044ba12b7649f9865c9ac8b36c2d6421c98396944b95d476003/debugger

**Comment by hrishikeshio** [comment]
This is probably happening due to divide by zero at line https://github.com/razor-network/contracts/blob/master/contracts/Core/RewardManager.sol#L160
due to` lowerCutoffsLastEpoch.length`  being 0.


The following line should be added at the start of the function 

`        if (lowerCutoffsLastEpoch.length  == 0) return;
`
Also, this function needs more tests if such simple cases are not caught in them.

**Comment by adi44** [comment]
> This is probably happening due to divide by zero at line https://github.com/razor-network/contracts/blob/master/contracts/Core/RewardManager.sol#L160
> due to` lowerCutoffsLastEpoch.length` being 0.
> 
> The following line should be added at the start of the function
> 
> ` if (lowerCutoffsLastEpoch.length == 0) return;`
> Also, this function needs more tests if such simple cases are not caught in them.

@hrishikeshio rewards are only being calculated if lowerCutOffsLastEpoch.length>0
https://github.com/razor-network/contracts/blob/1b9fcc1e6204f5a47c69cc1a0929bc7519a1e85b/contracts/Core/RewardManager.sol#L137

**Comment by hrishikeshio** [comment]
> > This is probably happening due to divide by zero at line https://github.com/razor-network/contracts/blob/master/contracts/Core/RewardManager.sol#L160
> > due to` lowerCutoffsLastEpoch.length` being 0.
> > The following line should be added at the start of the function
> > ` if (lowerCutoffsLastEpoch.length == 0) return;`
> > Also, this function needs more tests if such simple cases are not caught in them.
> 
> @hrishikeshio rewards are only being calculated if lowerCutOffsLastEpoch.length>0
> https://github.com/razor-network/contracts/blob/1b9fcc1e6204f5a47c69cc1a0929bc7519a1e85b/contracts/Core/RewardManager.sol#L137

Nope. That line is outside the if block.
