### ISSUE TITLE
Reduce the Complexity of givePenalties function

### ISSUE THREAD

**Issue by adi44** [razor-network/contracts#179]
//L76
function givePenalties(uint256 stakerId, uint256 epoch)
        external
        initialized
        onlyRole(parameters.getRewardModifierHash())
    {
        _givePenalties(stakerId, epoch);
    }

**Comment by GauravJain9** [comment]
https://github.com/razor-network/contracts/blob/master/contracts/Core/RewardManager.sol#L77

**Comment by hrishikeshio** [comment]
solved in #218
