### ISSUE TITLE
Staker might increase stake maliciously

### ISSUE THREAD

**Issue by adi44** [razor-network/contracts#180]
Staker might increase stake maliciously in givepenalties function.

**Comment by SkandaBhat** [comment]
Please add more context here. @adi44

**Comment by GaurShekhar** [comment]
Prior to 0.8.0 update of solidity , there can be a place where integer can overflows or underflows it's value and cause malfunction the code.

https://github.com/razor-network/contracts/blob/115ad2185d7b09ad10a830f52c74605e63dd49b1/contracts/Core/RewardManager.sol#L321

In the above line there can be a scene where penalty value overflows it's value and staker can increase it's stake maliciously.

Solution-

After the 0.8.0 update Arithmetic operations revert on underflow and overflow.

Conclusion -

Now after the latest update of solidity , this is no longer a issue.

**Comment by hrishikeshio** [comment]
remove the todo in a PR to resolve this issue
