### ISSUE TITLE
If the current stake is zero, staker should not be able to stake anymore

### ISSUE THREAD

**Issue by adi44** [razor-network/contracts#181]
There are a variety of ways current stake could become zero. (penalty, inactive penalties, withdraw, etc.).

We need to write tests to verify this is expected behaviour.

**Comment by adi44** [comment]
If we ban staker from adding stake after slash, staker can anytime use new address and stake funds.

**Comment by SkandaBhat** [comment]
Please add more context and link related issues.

**Comment by SkandaBhat** [comment]
We should add tests to check this scenario.

**Comment by SkandaBhat** [comment]
For more info, check https://github.com/razor-network/contracts/blob/master/contracts/Core/StakeManager.sol#L149
