### ISSUE TITLE
Inconsistent Numbering of assetId

### ISSUE THREAD

**Issue by abhishekvispute** [razor-network/contracts#182]
Hi Guys,
I think
There is one issue with assetId numbering
Sometimes its starting index considered as 1, sometimes 0

In assetManager we start assetId by 1

https://github.com/razor-network/contracts/blob/6a6b116155cb0b2e889c25f6c8389efd91021943/contracts/Core/AssetManager.sol#L82

But while storing revealed votes 
We start from 0

https://github.com/razor-network/contracts/blob/6a6b116155cb0b2e889c25f6c8389efd91021943/contracts/Core/VoteManager.sol#L94

https://github.com/razor-network/contracts/blob/6a6b116155cb0b2e889c25f6c8389efd91021943/test/VoteManager.js#L129

The same can be seen in blocks, there in medians, cutoffs we assume starting index of an asset as 0.
(This only saved us while calculating penalties and rewards as there we consider vote and block storage, and as both start from 0 now, it doesn't break)

As of now, one place I found where it breaks is in dispute, in giveSorted
https://github.com/razor-network/contracts/blob/6a6b116155cb0b2e889c25f6c8389efd91021943/contracts/Core/BlockManager.sol#L176
There we ask for assetId from staker,
Here staker has to pass assetId as per 0-> NumAssets-1, but from assetManager a Staker would know it as 1->NumAssets, raising an invalid dispute
The same can be seen in tests, their we are passing assetId -1 not assetId
https://github.com/razor-network/contracts/blob/6a6b116155cb0b2e889c25f6c8389efd91021943/test/BlockManager.js#L241

Please verify if its a genuine issue, If it is we have to thoroughly check where else its breaking

**Comment by SkandaBhat** [comment]
Lets start assetID from 0. This should solve the problem.
