### ISSUE TITLE
Small stakers will not get rewards for voting coherently

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/contracts#185]
**Describe the bug**
The reward formula will likely return 0 for small stakers since their stake will be very small compared to the stake getting a reward.

https://github.com/razor-network/contracts/blob/master/contracts/Core/RewardManager.sol#L158

This is not fair as they are still penalized for voting incoherently despite their small stake.

This sheet shows penalty and rewards calculations for a small staker 
https://docs.google.com/spreadsheets/d/1OrMB4Ya7RwtfmdYFjzicuIusUhb5-psKlvP36_WMEWA/edit?usp=sharing

This will cause slow value transfer from small stakers to big stakers.

**Comment by adi44** [comment]
Can we calculate the ratio of staker's stake and stakegettingreward, if its significantly low we can put reward x percentage of stake?

**Comment by hrishikeshio** [comment]
Preliminary simulations prove this issue exists.

https://github.com/razor-network/simulations/blob/master/rewards.ipynb

**Comment by SkandaBhat** [comment]
Closing this because it is covered in #213
