### ISSUE TITLE
How to handle scenario where elected proposer does not confirmBlock()

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/contracts#188]
what if the elected proposer does not confirmblock()?

1. we do call the calculations in propose()
  activeJobs() needs to be snapshotted
2. the first committer does calculations and gets a reward
  - complexity
3. confirmBlock() can be called by others
  -

**Comment by adi44** [comment]
@SkandaBhat  Does this solve the problem, if block is not confirmed in commit state, it calls confirm block.
https://github.com/razor-network/contracts/blob/115ad2185d7b09ad10a830f52c74605e63dd49b1/contracts/Core/VoteManager.sol#L53-L57

**Comment by SkandaBhat** [comment]
This is a non-issue. Closing this.
