### ISSUE TITLE
current penalty/reward formula doesn't provide equitable distribution

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/contracts#196]
**Describe the bug**
Currently, those who are penalized due to voting incoherently don't get rewarded.

This causes big stakers to get big penalties in accordance with their stake. The penalty is transferred to small stakers.

**Solution**
Those who are penalized should also get the rewards from reward pool.
OR adjust the penalty formula to get this outcome.

Simulation:
https://github.com/razor-network/simulations/blob/master/rewards.ipynb

**Comment by SkandaBhat** [comment]
This is replaced by #213 .
