### ISSUE TITLE
Use Safemath everywhere

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/contracts#20]
In some instances, normal math is used. Use openzeppelin safemath everywhere.

**Comment by dev1644** [comment]
This can be closed in favour of #73, Solidity 0.8.0 uses `SafeMath` under the hood.

**Comment by abhishekvispute** [comment]
Under PR for #73, we will include both issues

**Comment by SkandaBhat** [comment]
Closing this as it is handled in #73.
