### ISSUE TITLE
updateAssetStatus() functions in opposite way than expected

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/contracts#203]
**Describe the bug**
calling updateAssetStatus() with isActive = true should activate the job. 

However, it deactivates the job which is counterintuitive.

it should activate the job/collection.

Also, the If statement here is redundant
https://github.com/razor-network/contracts/blob/master/contracts/Core/AssetManager.sol#L171

Can be replaced with simply
```
jobs[id].active = isActive;
```

**Comment by SkandaBhat** [comment]
Naming it setAssetStatus seems intuitive in this case.
