### ISSUE TITLE
Add tolerance for reporting

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/contracts#204]
**Is your feature request related to a problem? Please describe.**
currently, if the reported value is different by even <0.0001, the staker will get a penalty

**Describe the solution you'd like**
create a configurable tolerance so that may be upto 1% deviation will not be penalized.

**Comment by SkandaBhat** [comment]
1% seems too much. But agree on the configurable tolerance.

**Comment by SkandaBhat** [comment]
Closing this because it is covered in #213 .
