### ISSUE TITLE
add escape hatch

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/contracts#208]
**Is your feature request related to a problem? Please describe.**
in case of a bug, allow admin to remove all staked tokens as a precaution. 

**Describe the solution you'd like**
during the beta phase, allow admin to withdraw all tokens. the feature should be disabled when the network is stable. Alternatively, the feature can be kept and admin access can be handed over to multisig.

**Comment by adi44** [comment]
@hrishikeshio Basically we need to include a exit function for admin so in case of bug, admin can withdraw all the funds?

**Comment by hrishikeshio** [comment]
> @hrishikeshio Basically we need to include a exit function for admin so in case of bug, admin can withdraw all the funds from stakemanager contract?

yes
