### ISSUE TITLE
AssetModifier migration bug

### ISSUE THREAD

**Issue by SamAg19** [razor-network/contracts#215]
**Describe the bug**

https://github.com/razor-network/contracts/blob/132a0b293d48cb313b85b524567e746ec8e4fc2a/migrations/src/postDeploymentSetup.js#L71

This needs to be changed from stakeManager to assetManager in the migration script as AssetModifier role is being used in assetManager

**Comment by hrishikeshio** [comment]
what happened? the bug is reintroduced? @SkandaBhat
