### ISSUE TITLE
Half of the slashed stake does not get burnt

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#220]
@GauravJain9 please add more info here.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by abhishekvispute** [comment]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/566a774222707e424896c0c390a84dc3c13bdcb2/contracts/token/ERC20/ERC20.sol#L274

In RAZOR we can add a wrapper around this burn and give access to only concerned contarct.
