### ISSUE TITLE
Tests fail sometimes on circlici

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#254]
**Describe the bug**
Tests on circleci sometimes fail

**To Reproduce**
Check https://app.circleci.com/pipelines/github/razor-network/contracts/35/workflows/e774ef78-d03b-48bc-a41b-36132e081a7b/jobs/62

**Comment by GauravJain9** [comment]
Hey @SkandaBhat  on my latest PR I think it's only running tests for ACL and then exits and says tests passed

**Comment by GauravJain9** [comment]
https://circleci.com/api/v1.1/project/github/razor-network/contracts/151/output/102/0?file=true&allocation-id=6102712c8b0d9d35476ea875-0-build%2F49056AEF

https://app.circleci.com/pipelines/github/razor-network/contracts/54/workflows/9b2c8418-17c2-46f7-8f5a-75336740f671/jobs/151/parallel-runs/0/steps/0-102

**Comment by SkandaBhat** [comment]
Closing this as related features have been removed.
