### ISSUE TITLE
CircleCI: Publish NPM package on tag creation

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#256]
We need to add a job on CircleCI to publish an npm package whenever a tag is created.

**Comment by hrishikeshio** [comment]
@SkandaBhat please unassign if you are not working on this

**Comment by SkandaBhat** [comment]
More analysis is still needed for this. There is a risk of npm keys being leaked from circle CI as we are sharing them to forked repos as well. For now, we can keep on hold and look into it later.

**Comment by SkandaBhat** [comment]
Waiting to resolve #499 before picking this up.

**Comment by SkandaBhat** [comment]
We will do this manually for now. There are security concerns regarding sharing npm keys with circleci.
