### ISSUE TITLE
Reset Lock can be called before withdraw after is over.

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#260]
@GauravJain9 please add more info here.

**Comment by GauravJain9** [comment]
Here the staker can call resetlock even during the lockperiod i.e. without the lock being expired and is violating https://github.com/razor-network/contracts/blob/08c79eaa5e115e2ab61208dff781aaf80d34b219/contracts/Core/StakeManager.sol#L356
 
Don't exaclty know the consequences !  @SkandaBhat @abhishekvispute 

1) As per the discussion during meeting it should not affect anything other than the staker getting penalized
2) Some discussion also revolved around handling this in razorscan don't know exactly @ashish10677 can add info

**Comment by ashish10677** [comment]
Razorscan can handle this scenario by disabling the resetLock button till the lock period is not expired. This will prevent users from using the resetLock unnecessary and losing funds.

**Comment by SkandaBhat** [comment]
Closing this issue as it is not causing any problems.
