### ISSUE TITLE
add multiplier

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/contracts#266]
add multiplier to denote the number of decimals.

eg. eth value is 3123.34

in job/collection,set multiplier is 1000000

then value 31233440 should be reported

the multiplier can be used in razorscan to reconvert the integer to decimals by dividing the result by multiplier

**Comment by abhishekvispute** [comment]
picking this up

**Comment by abhishekvispute** [comment]
> the multiplier can be used in razorscan to reconvert the integer to decimals by dividing the result by multiplier.

Hey @hrishikeshio,
Do we want division as specified in this issue or multiplication as specified in https://github.com/razor-network/contracts/pull/278#discussion_r685088322
Both problems are diff I think

**Comment by hrishikeshio** [comment]
both are specifying multiplication on client side.
division will be done on consumer side (razorscan and client dapps)
