### ISSUE TITLE
Potential hash collision

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/contracts#303]
**Describe the bug**
A potential hash collision maybe possible in reveal() 

more details:
https://solidity-by-example.org/hashing/

** possible solution **
use abi.encode() instead

**Comment by SkandaBhat** [comment]
Write tests to validate the hypothesis first.

**Comment by abhishekvispute** [comment]
Hi, Guys @razor-network/engineering,

So this issue says that for ```abi.encodepacked("aa", "aaa")``` and ```abi.encodePacked("a","aaaa" )``` hash would collide.
Yes this is true, as the following code snippet, proves
but it's not applicable for uint

Results :

aa,aaa
0x5aff159202c5d82ecfd14de49cc2c8c1f74964a25d78c549137c4ce714030fe7

aaa,aa
0x5aff159202c5d82ecfd14de49cc2c8c1f74964a25d78c549137c4ce714030fe7

11,11
0x1353ecfdccff48323b2be6cf164fa066146837691b44694c0f716a1e19a76f97

1, 111
0x5b27e4352d112d168fcd702d60655a76f94e21cb7e9f2ad225ad84de91e8c34b

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract HashFunction {
    
    function hashString(string memory x, string memory y)
        public pure returns (bytes32)
    {
        return keccak256(abi.encodePacked(x, y));
    }
 
   
    function hashUint(uint48 x, uint48 y)
        public pure returns (bytes32)
    {
        return keccak256(abi.encodePacked(x, y));
    }   
    
    function hashValuesUintArray(uint48 [] memory values)
        public pure returns (bytes32)
    {
        return keccak256(abi.encodePacked(values));
    }   
    
    
    // function hashValuesStringArray(string [] memory values)
    //     public pure returns (bytes32)
    // {
    //     return keccak256(abi.encodePacked(values));
    // }   
}
```

In our, case we use encodePacked in the reveal  
https://github.com/razor-network/contracts/blob/3064370a06b5bb9d7369098c8ec6d24755c48bc5/contracts/Core/VoteManager.sol#L73

we have [epoch, values, secret]
epoch, values are unit only

so it does not apply to our case

**Comment by hrishikeshio** [comment]
Makes sense
