### ISSUE TITLE
Write a test case to check finalizeDispute should not work if total Influence Reward does not match

### ISSUE THREAD

**Issue by shekhar2807** [razor-network/contracts#328]

**Comment by hrishikeshio** [comment]
why was this reopened? @shekhar2807 @SkandaBhat

**Comment by shekhar2807** [comment]
> why was this reopened? @shekhar2807 @SkandaBhat

@hrishikeshio sir , The test cases were passing locally and in the build of PR but after merging to the master the build was failing , so we reverted the PR and then I opened the issue again.

**Comment by SkandaBhat** [comment]
This has been included in #350. Closing.
