### ISSUE TITLE
Network will break when collection is deactivated.

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#336]
The only issue of solving it in this way is that if we decide to deactivate an asset, it will start pointing to the wrong assetID again.

_Originally posted by @SamAg19 in https://github.com/razor-network/contracts/pull/334#discussion_r690974577_

**Comment by hrishikeshio** [comment]
I think maintaining activeAssets[] might be more optimal solution than fulfullAssets()

updating active assets only needs to happen when collection is activated or deactivated. The complexity is O(1) with swap and pop method.

Fulfullassets has O(N) complexity and has to happen every epoch.

@SamAg19
