### ISSUE TITLE
move build/ out of repo

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/contracts#35]
build can be its own repo. All other razor network repos can refer to that folder.

this needs all dependent razor network repos to be modified.

**Comment by SkandaBhat** [comment]
- Import build folder from its own repos (Contracts and Bridge).
- Refactor throughout projects
- Delete/add to .gitignore build folders throughout projects

**Comment by SkandaBhat** [comment]
We have npm module now, this issue is fixed.
