### ISSUE TITLE
Event should be emitted while calling resetLock

### ISSUE THREAD

**Issue by rajkharvar** [razor-network/contracts#363]
Currently, no event is emitted when resetLock is called. 

If the event is triggered then it becomes easy to check the locks existing on the delegator while performing unstake or withdraw.

Consider the withdrawal period is in between N and N+5 epoch but if the delegator has already called resetLock in N+1 epoch, but from the withdrawal period it looks like delegator can only unstake after N+5 epoch. That's not the case here.

Hence if we get an event we can enable the unstake button for the delegator after the resetLock is called.

**Comment by adi44** [comment]
@rajkharvar What parameters you need in this event?

**Comment by rajkharvar** [comment]
I think stakerId and epoch would be enough.

**Comment by adi44** [comment]
we would need to get epoch from storage since in resetLock method. @rajkharvar @hrishikeshio
