### ISSUE TITLE
To add the functionality of changing default admin in access control to ensure flexibility.

### ISSUE THREAD

**Issue by abhishekvispute** [razor-network/contracts#39]
To add the functionality of changing default admin in access control to ensure flexibility.
Obviously, only the current admin can pass his role to the new one.

In Todays Scenario,
It's fixed to one who deploys the contract initially.

**Comment by SkandaBhat** [comment]
Assigned to @abhishekvispute

**Comment by SkandaBhat** [comment]
Closed.
