### ISSUE TITLE
Staker can avoid inactivity penalties by unstaking a small amount every epoch

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#392]
**Describe the bug**
Right now, inactivity penalties are given out during unstake and the staker's unstake action is updated which prevents him from getting a penalty when the staker commits in the next epoch.

The staker can bypass inactivity penalties during commit state by unstaking a very small amount of razors every epoch, thereby not taking voting in the network.

**Comment by SamAg19** [comment]
picking this as the solution for #396 is same for this as well
