### ISSUE TITLE
Should we render penalty if stake is lesser than min stake?

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#397]
Should lock penalty and inactivity penalty be applied if stake < minstake?

**Comment by adi44** [comment]
picking this up

**Comment by SamAg19** [comment]
@hrishikeshio @abhishekvispute @SkandaBhat 
How about we give out inactivity penalties to all the stakers just before we change minStake when we call setMinStake function in Parameters? The gas costs will be incurred by us here as the admin can only call this function

**Comment by SamAg19** [comment]
Inactivity penalties to be applied regardless of stake being less than minStake.
