### ISSUE TITLE
Test unstake and withdraw

### ISSUE THREAD

**Issue by agatsoh** [razor-network/contracts#4]
Test where staker unstakes and is made to wait for one epoch which is the unstake lock period
1. test that before unstake lock period staker is not able to unstake
2. test that after unstake lock period staker is able to unstake 

Test where staker unstakes he is made to wait for withdraw lock period after which he able to withdraw staked amount
1. test that before withdraw lock period staker is not able to withdraw
2. test that after withdraw lock period staker is able to withdraw the stake amount

**Comment by hrishikeshio** [comment]
resolved
