### ISSUE TITLE
Reason can be added in StakeChange event

### ISSUE THREAD

**Issue by rajkharvar** [razor-network/contracts#402]
**Is your feature request related to a problem? Please describe.**
Before v0.1.6, the `reason` was being emitted in StakeChange event which shows "Block Reward" or "Inactivity Penalty" for any staker. But as per now, it's removed

**Describe the solution you'd like**
If the `reason` is emitted in StakeChange it becomes easy for the user to check the stake change is happening due to which reason. If the action is not available then it becomes slightly difficult to predict the cause of stake change

**Comment by hrishikeshio** [comment]
An enum can be used instead as string is too expensive.
