### ISSUE TITLE
What is the purpose of setStakerStake() in StakeManager?

### ISSUE THREAD

**Issue by abhishekvispute** [razor-network/contracts#41]
function setStakerStake(uint256 _id, uint256 _stake, string calldata _reason, uint256 _epoch) external onlyWriter {
        _setStakerStake(_id, _stake, _reason, _epoch);
  }
This Function is not called in any other contracts.
In comments of VoteManager, there is one call of it 
So was it created for test purposes only?

**Comment by SkandaBhat** [comment]
Assigned to @abhishekvispute

**Comment by SkandaBhat** [comment]
Closed.
