### ISSUE TITLE
Multiple Snitch for same mal activity if staker is slashed for less than 100%

### ISSUE THREAD

**Issue by abhishekvispute** [razor-network/contracts#413]
Our slashing penalty is customizable, right now its 100 %
https://github.com/razor-network/contracts/blob/ef7dd744ece41079257d4591ec7cfc46a24b41ca/contracts/Core/StakeManager.sol#L298

The issue arises when we make it < 100 %

Right now anyone cant snitch over the same mal activity, as once snitched stakers stake is reduced to 0, now from there if I again snitch, my bounty would be 0 only

this doesn't apply when slashing is < 100 %

Stake 1000
Slashing Penalty = 50% = 500, award 250 to bountyHunter
Stake 500
Slashing Penalty = 50 % = 250 , award 125 to boutyHunter
....
....
and it goes on
....

Hence at end even if we keep penalty < 100%,  staker could lose all

**Comment by GauravJain9** [comment]
Can we add    " require(commitments[thisStakerId].commitmentHash  != 0x0)"  because it will be set to 0 the first time anyone calls snitch ?

**Comment by SkandaBhat** [comment]
Write a test to validate and close this issue.
