### ISSUE TITLE
Proposed Block not being inserted appropriately

### ISSUE THREAD

**Issue by SamAg19** [razor-network/contracts#428]
**Describe the bug**
Proposed blocks are not being sorted properly based on their iteration due to the issue in the following if condition:
https://github.com/razor-network/contracts/blob/9521cdf965dbe59c2ba414c21417b7041f59bb31/contracts/Core/BlockManager.sol#L242

Here, it is trying to sort serially whereas it should be sorting based on the sortedProposedBlockIds array

**Comment by hrishikeshio** [comment]
duplicate of https://github.com/razor-network/contracts/issues/415 ?

**Comment by hrishikeshio** [comment]
@abhishekvispute had already started working on #414 which is a duplicate of this issue.

Please check open issues properly next time @SamAg19

**Comment by SamAg19** [comment]
Should i close this issue and its respective PR then?

**Comment by hrishikeshio** [comment]
Discuss with @abhishekvispute

**Comment by SamAg19** [comment]
This issue was mainly created due to an error of sorting the blocks that was found while testing insertAppropriately 
@hrishikeshio

**Comment by abhishekvispute** [comment]
Hi Guys,
Nw @SamAg19 
You can go ahead with your PR
Please uodate it in first if as well
