### ISSUE TITLE
[Epic] Track and resolve Issues that come up on Tenderly

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#441]
- [x] #442

**Comment by SkandaBhat** [comment]
https://dashboard.tenderly.co/razor/razor-network/tx/mumbai/0x46cd8389f6791590b8c3eeed65a9dc8e493ab09725694e2b7ab0fe979f63cbce/debugger?trace=0

**Comment by abhishekvispute** [comment]
Closing as nothing open now
