### ISSUE TITLE
combine denominator parameters such as penalty denominators

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/contracts#460]

**Comment by GauravJain9** [comment]
For all the num there will be a single denom what should be the name of the variable can it be 'denom' ? @hrishikeshio

**Comment by abhishekvispute** [comment]
Hey @GauravJain9 
Sorry I forgot to assign myself
Have already resolved this issue

**Comment by GauravJain9** [comment]
oh ok cool @abhishekvispute
