### ISSUE TITLE
If biggestInfluencer is incorrect, delete the block

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/contracts#467]
Currently if biggest influencer in proposed block is incorrect, we just move it further in the priority queue 

https://github.com/razor-network/contracts/blob/master/contracts/Core/BlockManager.sol#L247

However, the block is proven to be invalid since it provided incorrect biggestInfluencer. Hence the block should be replaced by the new proposed block.

In a separate issue, we can consider slashing the incorrect block proposer

**Comment by abhishekvispute** [comment]
picking this up
