### ISSUE TITLE
[Epic] Optimisations

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#491]
List down all possible optimisations here.

- [x] #490 
- [x] #500
- [x] #554
- [x] #519
- [x] #433 
- [x] #503
- [x] #546
- [x] #502 
- [x] #522

**Comment by hrishikeshio** [comment]
influence function maybe optimised as below:
maturity = log ( age)
influence = log(stake) * log(age)
influence = log(stake + age)
