### ISSUE TITLE
Stake needs to be uint128

### ISSUE THREAD

**Issue by abhishekvispute** [razor-network/contracts#519]

**Comment by shekhar2807** [comment]
Hey @razor-network/contract-core,
According to my analysis , stake can't be uint128.

Reasons-

1) Staked Token inherits IERC20 contract which returns uint256 , after implicitly converting it to uint128 it overshoots the StakeMnager contract size.

2) Even after running optimizer, _convertRZRtoSRZR and _convertSRZRToRZR overflows as their is multiplication in these functions.

So, acccoring to me after convering stake to uint128 and imlicitly converting to uint128 in many places it dose't optemize anything. If there is anything else need to be done,please mention it here.

**Comment by SkandaBhat** [comment]
Closing this.
