### ISSUE TITLE
Check if dividing stake by large number beforehand makes a difference in consumption for influence calculation

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#546]

**Comment by SamAg19** [comment]
Not much change in gas costs by applying bitwise shift. Minimal increase in gas cost of reveal actually where getInfluence is being called. I don't think so it is required to implement this

@SkandaBhat @hrishikeshio @abhishekvispute

**Comment by SkandaBhat** [comment]
Closing this.
