### ISSUE TITLE
Use FullMath mulDiv in case of RZR <> sRZR conversion

### ISSUE THREAD

**Issue by abhishekvispute** [razor-network/contracts#555]
when there is 
(uint256 * uint256) /  uint256 
num can overflow 

there is standard lib to solve this issue 
https://github.com/Uniswap/v3-core/blob/main/contracts/libraries/FullMath.sol
```
Handles "phantom overflow" i.e., allows multiplication and division where an intermediate value overflows 256 bits
```

**Comment by adi44** [comment]
will pick this up

**Comment by hrishikeshio** [comment]
What is the scenario where it will overflow.
I would prefer to solve the issue in a different way rather than introducing a whole new library.

**Comment by abhishekvispute** [comment]
like here 
https://github.com/razor-network/contracts/blob/08296c14add44adc40e64b0040dc2461627a6dcf/contracts/Core/StakeManager.sol#L444

where we are multiplying amountInRZR with totalSupplyOfSRZR 
both can technically be uint256 
hence their multiplication is possible to overflow uint256 

now how large no should be for this to happen lmc

**Comment by hrishikeshio** [comment]
I need practical scenario. What are the practical numbers where this can happen. E.g. RZR supply is limited to 1B so this may not happen.

**Comment by abhishekvispute** [comment]
oh yep, with our cap of (10^9 * 10^18) this won't happen 
we can close this issue
