### ISSUE TITLE
Staker stake has to be greater than minstake in order for delegate to work.

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#562]
https://dashboard.tenderly.co/tx/mumbai/0xbeb00bbd380cf742092239987dcb8387335ef451aa88b1b895fa2bb1abead111/debugger?trace=0.3

https://dashboard.tenderly.co/tx/mumbai/0x8dc5dbcc134a7902e410cf86d1613501089ea2821471757045cdc978155248d4/debugger?trace=0.0

**Comment by hrishikeshio** [comment]
#563 should solve the issue.

**Comment by hrishikeshio** [comment]
this shouldnt be done. 
e.g. in scenario minstake is 10k and staker stakes 10k
she is inactive and gets 10 razor penalty making his stake below minstake.
causing delegate and stake to be disabled.

**Comment by SamAg19** [comment]
Closing this issue
