### ISSUE TITLE
If staker is slashed, he must not be able to participate anymore.

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#563]
We need to prevent cases like this from happening again, where if the stake after slashing is a small number but not zero, then the total supply results in a huge number.

https://dashboard.tenderly.co/tx/mumbai/0xbeb00bbd380cf742092239987dcb8387335ef451aa88b1b895fa2bb1abead111/debugger?trace=0.3

**Comment by adi44** [comment]
Picking this up next

**Comment by adi44** [comment]
Should we prevent staker from commiting also? @razor-network/contract-core
