### ISSUE TITLE
merkle tree verification optimisations

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#582]
- [x]  ask for an additional parameter which specifies position of hash in the proof.
e,g, (concatenated proof, Ta, 010111)
where each bit of 010111 specified the position of each hash in the next hash. (left or right) [required] [not doing]

- [ ] Add a caching layer to optimise processing time and reduce

1. cache all provided and calculated hashes.  (Or only proven hashes?)
2. return / stop verification when a hash is calculated which already exists in cache and is already verified to be part of merkle root.

e.g. for TA; proof = {TA, HB, HCD, HEFGH}
For TC; proof = {TC, HD, HAB, HEFGH}
But, for TC, H(H(TC), HD) = HCD. which is already verified in step 1 to be part of merkle root. Hence verification can stop here. rest of verification is not required.

- [x] 1. Restrict the proof length and effectively tree length to a predefined number e.g.4 if required

**Comment by abhishekvispute** [comment]
Todos

- [ ] Client Side to create our version of merkle tree and getProof
- [ ] Modify contract of Merkle with position and get sequence
- [ ] Optimise get sequence (Number to Binary Optimisation and can we use something diff than bytes to store bin)
- [ ] Catching
- [ ] Testing

**Comment by abhishekvispute** [comment]
This is done and a separate repo has been created 
https://github.com/razor-network/position-aware-merkle
Hence closing
