### ISSUE TITLE
Staker gets Randao Penalty if delegator unstakes after it commits in Epoch N

### ISSUE THREAD

**Issue by adi44** [razor-network/contracts#585]
https://dashboard.tenderly.co/tx/mumbai/0x532c8249167464bea1daf8249d5eaca606ec7d14c1ddafa99d6e1ac71fa74854/debugger?trace=0.2.1.3

Staker had revealed in epoch N-1 and committed in epoch N. Now delegator comes and unstakes the amount, the staker has to pay randao penalty because of the following code 

`if (epochLastRevealed < epochLastCommitted) {
            uint256 randaoPenalty = newStake < blockReward ? newStake : blockReward;
            newStake = newStake - randaoPenalty;
        }`

here epochLastRevealed = N-1 and epochLastCommitted = N

**Comment by SkandaBhat** [comment]
Possible solution: Allow unstake during confirm state only.

**Comment by SkandaBhat** [comment]
Penalise only if stake < minstake

**Comment by GauravJain9** [comment]
Picking this up !

**Comment by SkandaBhat** [comment]
#135 will fix this. Hence closing this.
