### ISSUE TITLE
Do not reduce age on inactivity

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#587]
Reducing it to 0 directly is harsh, have fair mech

**Comment by hrishikeshio** [comment]
I think better to reduce age by 1 per epoch of inactivity.

**Comment by GauravJain9** [comment]
picking this up !

**Comment by GauravJain9** [comment]
> I think better to reduce age by 1 per epoch of inactivity.

Currently we are reducing it by 10000 per epoch !

**Comment by SkandaBhat** [comment]
Will be fixed by implementing #599
