### ISSUE TITLE
[Proposal] Consensus algorithm improvements

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/contracts#592]
Changes to improve consensus algorithm:

Currently we are using proof of influence algorithm. This highly incentivizes manipulating votes to increase maturity since it 
can boost influence immensely.

- We should switch to proof of stake algorithm. _isElectedProposer() should use stake and not influence.
- Influence will still be used to calculate median
- age penalty calculation should have customizable permissible error (i would suggest 10% as default) to 
avoid strong bias towards big maturity stakers and make it difficult for small maturity stakers to grow their maturity.
- Influence calculation should change to following
  Influence = 0.9*N(stake) + 0.1*N(maturity)
  Where N() is a normalization function. Since stake and maturity have different orders of magnitude, they need to be normalized.
- inactivity penalty on age = 1 per inactive epoch 
- randao penalty on age = 100% (set age to 0)
- to disincentivize malicious voting, allocate part of block reward based on maturity.
e.g. block reward = 90 + 10*staker_maturity/max_maturity
- once dispute mechanism is integrated, a validator can be bought to jury in case of malicious voting, strongly punishing this behavior.
Till then we can use the mechanism above.

**Comment by abhishekvispute** [comment]
Hmm if we go with 
block reward = 90 + 10*staker_maturity/max_maturity

and my chance of block reward is only proportional to stake 
There is no stopping me from voting incoherently, 
my chances of block reward are proportional to stake, which won't change with incoherent voting 

should we make block reward function of maturity directly ?
you are selected as a isElectedProposer on basis of stake but the reward you get is proportional to maturity.

hmm but again issue arise that the bigger influencer holders manipulate vote such that age of other stakers don't increase.
so intern then will not earn any rewards

**Comment by abhishekvispute** [comment]
What was the core reason for bringing influence ? 
What was its advantage in being there for isElectedProposer and Voting ?

Was it that 
A new staker with huge funds should not be able to manipulate network before earning the age

**Comment by hrishikeshio** [comment]
Updated proposal:

Changes to improve consensus algorithm:

Currently we are using proof of influence algorithm. This highly incentivizes manipulating votes to increase maturity since it
can boost influence immensely.
 
- We should switch to proof of stake algorithm. _isElectedProposer() should use stake and not influence.
- Influence will still be used to calculate median
- age penalty calculation should have customizable permissible error (i would suggest 2% as default) to avoid strong bias towards big maturity stakers and make it difficult for small maturity stakers to grow their maturity.
- permissible error should be adjusted per collection basis by governance
- Influence calculation should change to following
- Influence = N(stake) *N(maturity)
- Where N() is a normalization function. Since stake and maturity have different orders of magnitude, they need to be normalized. (Should be confirmed?)
- inactivity penalty on age = 1 per inactive epoch
- randao penalty on age = 100% (set age to 0)
- once dispute mechanism is integrated, a validator can be bought to jury in case of malicious voting, strongly punishing this behavior.

**Comment by SkandaBhat** [comment]
convert this to an epic @SkandaBhat
