### ISSUE TITLE
AgeChange reason emitted bug

### ISSUE THREAD

**Issue by yohanelly95** [razor-network/contracts#631]
- If the `age` increases or decreases, currently `VotingPenalty` is emitted as the age change reason. This can be confusing, since on Razorscan for an increased age the reason will show as `VotingPenalty`. For a decreased age, we can continue to emit VotingPenalty. 
- `enum AgeChanged {
        InactivityPenalty,
        VotingPenalty
    }`

**Comment by SkandaBhat** [comment]
Rename `VotingPenalty` to `VotingRewardOrPenalty`.
