### ISSUE TITLE
Free unstake from state restrictions

### ISSUE THREAD

**Issue by abhishekvispute** [razor-network/contracts#659]
Commit 
Reveal => Randao

Propose
Dispute => Hit and Run

**Comment by abhishekvispute** [comment]
right now its only confirm

**Comment by abhishekvispute** [comment]
commit and reveal would be saved by AAR
For propose and dispute we have to see,
With P + e PR, issue is shifted to withdraw

**Comment by SkandaBhat** [comment]
analysis of this can be done only after AAR is reviewed/merged. So after reviewing, this can be discussed and be finalised upon

**Comment by abhishekvispute** [comment]
Unstake should be open for all states
InitiateWithdraw should be restricted in propose and dispute

**Comment by GauravJain9** [comment]
Right now initiatewithdraw can happen in any state except propose and dispute
Unstake can happen in any state

**Comment by abhishekvispute** [comment]
Closing this as per above analysis 
We would need to have initiateWithdraw not allowed in propose and dispute 
To cancel out hit and run attack from staker
As that moment sRZR to RZR conversion is done.

CC : @hrishikeshio @SkandaBhat @SamAg19
