### ISSUE TITLE
Dissolve Constants library, declare constants into contract if needed.

### ISSUE THREAD

**Issue by dev1644** [razor-network/contracts#75]
This issue is about to dissolve `Constants.sol` library, declare constants into the contract if needed.

This has following benefits -:

- As constants are inlined in Solidity, we would be saving some execution cost too. When we fetch constants from Library it uses delegate call which adds up the cost of tx. (~2000 gas)
- Almost all of the constants declared in `Constnats.sol` are exclusive to a single contract, it will improve code readability too.

**Comment by hrishikeshio** [comment]
if we change the constants, then we will have to edit it everywhere.
and if we forget to edit in one of the contracts, it can be a disaster
also there are not really constants but rather governance parameters
these need to be changeable by admin and then later by the dao

**Comment by dev1644** [comment]
I see @hrishikeshio , so if these Constant are subject to change then it would be better if they exist in their own separate contract. Other contracts can fetch the value and use it. Constant/Governance Contract would also have a way to edit these values through admin/DAO access.
