### ISSUE TITLE
Integrate Sol Coverage in CI and add respective badges <EOM>

### ISSUE THREAD

**Issue by abhishekvispute** [razor-network/contracts#78]

**Comment by hrishikeshio** [comment]
The solcver sometimes fails due to unknown reasons. currently forcing build to succeed even if coverage job fails.

**Comment by hrishikeshio** [comment]
@SkandaBhat @abhishekvispute

**Comment by abhishekvispute** [comment]
Yes @hrishikeshio, I also faced this issue
I was not sure if it's my machines issue only or in general
IMO
We have to increase the timeout limit for solCoverage
I had added the following in the hardhat config, and then it was successful

```
 mocha: {
    timeout: 5000000  (legitimate up limit we have to find)
  }
 ```
 
by default it's 20000 I think
