### ISSUE TITLE
[Testing] Test deployment from ledger

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#794]

**Comment by SkandaBhat** [comment]
Acceptance criteria:

Notion Document explaining the issue and solution
Notion Document explaining tradeoffs and potential issues
Notion Document to include List of changes that need to be done

**Comment by SamAg19** [comment]
https://www.notion.so/razorto/Post-deployment-using-ledger-25fa8e4cb88143d48e7f64c84f0e8495
