### ISSUE TITLE
[Post Deployment Script] Only transfer tokens in testnets: make the network check explicit

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#818]
In https://github.com/razor-network/contracts/blob/master/migrations/src/postDeploymentSetup.js#L36, we need to be explicit in mentioning the network as "testnet" instead of !== "mainnet".

This needs to be done in v1 as well.

**Comment by SamAg19** [comment]
Having to reopen the issue due to it being merged in the wrong branch
