### ISSUE TITLE
[Analysis] Why are we allowing stakers to call commit even though stake < minStake

### ISSUE THREAD

**Issue by SamAg19** [razor-network/contracts#860]

**Comment by SamAg19** [comment]
If we replace require with an if then the changes that take place in `givePenalties` regarding age and stake and in `confirmPreviousBlockEpoch` where the block is confirmed and values are set of proposed ids wont go through

https://github.com/razor-network/contracts/blob/1d56fa10f563da191c35bf244ca3023b5972d233/contracts/Core/VoteManager.sol#L92

https://github.com/razor-network/contracts/blob/1d56fa10f563da191c35bf244ca3023b5972d233/contracts/Core/VoteManager.sol#L89

**Comment by yohanelly95** [comment]
Closing issue, changes not required
