### ISSUE TITLE
[Analysis] why are we not using collectionID instead of leafID in all vote mappings after verifying from merkle tree

### ISSUE THREAD

**Issue by SamAg19** [razor-network/contracts#861]
Right now votes, voteWeights and totalInfluenceRevealed is stored wrt leaf ID

https://github.com/razor-network/contracts/blob/101d9eb33c7be8e466f517e6ace593e36742b540/contracts/Core/VoteManager.sol#L168

Why cant we convert leafID to collectionID after merkle proof verification? In all dispute cases, we are either getting collectionID from leafID to finalize dispute
https://github.com/razor-network/contracts/blob/101d9eb33c7be8e466f517e6ace593e36742b540/contracts/Core/BlockManager.sol#L427

Or getting leaf ID from collection ID to query for vote-related details from voteManager. By storing it with collectionID, such calls wont be required anymore
https://github.com/razor-network/contracts/blob/101d9eb33c7be8e466f517e6ace593e36742b540/contracts/Core/BlockManager.sol#L337

**Comment by SamAg19** [comment]
After going through the contracts, Here are my 2 major observations: 

- I don't see any reason why we should continue using leafId in all vote mappings. We can convert leafId to collectionId after merkle tree verification. This will remove unnecessary external calls we make to the collectionManager for leafId to collectionId conversions and vice versa. 
- By converting to leafId to collectionId, we can remove `collectionIdToLeafIdRegistryOfLastEpoch` and `collectionIdToLeafIdRegistry` registries from collectionManager as well remove the function `updateDelayedRegistry` as this updates only the `collectionIdToLeafIdRegistryOfLastEpoch` which will be removed. This will save a lot of storage and updation gas costs

**Comment by SkandaBhat** [comment]
@SamAg19 Please create a new issue for implementation.
