### ISSUE TITLE
Deployment architecture diagram

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#920]

**Comment by yohanelly95** [comment]
High level overview of current hardhat deployment architecture - [https://lucid.app/lucidchart/6a277682-0e84-413f-817b-1045143b9c3e/edit?viewport_loc=-175%2C-60%2C2704%2C1256%2C0_0&invitationId=inv_9a23ba4f-d420-4c9c-a102-96386dbc89c1#](Diagram)

**Comment by yohanelly95** [comment]
Added the deployment architecture diagrams here https://www.notion.so/razorto/Deployment-Architecture-b1874c7547c848fb949cfbefcf8e7ba1
